#!/usr/bin/env Rscript
local({
  args <- commandArgs(TRUE)
  if (length(args) == 0L) {
    stop("Usage: twinkle <command> [<args>...]", call. = FALSE)
  }
  entrypoint <- getExportedValue("twinkle", args[[1L]])
  do.call(entrypoint, list(args[-1L]), envir = .GlobalEnv)
})
