#!/bin/bash
if [ -z "$TWINKLE_LOGS" ]; then
  echo "Expected environment variable 'TWINKLE_LOGS' to be set"
  exit 1
fi

if [[ $# -ne 1 ]]; then
    echo "Usage: delete-old-logs <days-old>"
    exit 1
fi

AGE=$1

if [[ $AGE -lt 10 ]]; then
    echo "Refusing to delete logs that are so young"
    exit 1
fi


find "$TWINKLE_LOGS" ! -ctime "-${AGE}" -type f -name '*.log' -delete
