#!/usr/bin/env bash
set -e

ROOT=$(realpath $(dirname $0)/..)
CALLER_UID=`id -u`
CALLER_GID=`id -g`
TWINKLE_TAG=$(cat $ROOT/twinkle_tag)
IMAGE=mrcide/shiny-server-builder:${TWINKLE_TAG}
if [ -z $TWINKLE_NO_PULL ]; then
    docker pull $IMAGE
fi

docker run \
  --rm \
  -v ${PWD}:/target \
  -w /target \
  --user="${CALLER_UID}:${CALLER_GID}" \
  mrcide/shiny-server-builder:${TWINKLE_TAG} \
  init
