#!/usr/bin/env bash
set -e
HERE=$(realpath $(dirname $0))
IMAGE_NAME="mrcide/haproxy"

TAG_GIT_SHA=$(git rev-parse --short=7 HEAD)
TAG_VERSION=$(cat $HERE/../version)

docker build --rm \
       --tag "${IMAGE_NAME}:${TAG_GIT_SHA}" \
       --tag "${IMAGE_NAME}:${TAG_VERSION}" \
       $HERE

if [[ "$TWINKLE_PUSH" = "true" ]]; then
    docker push "${IMAGE_NAME}:${TAG_VERSION}"
    docker push "${IMAGE_NAME}:${TAG_GIT_SHA}"
fi
