#!/usr/bin/env bash
ROOT=$(realpath $(dirname $0)/..)
VOLUME_BASE=$(basename $ROOT)
VOLUME="${VOLUME_BASE}_applications"
docker volume create $VOLUME
docker run -it \
       -v "${ROOT}:/src:ro" \
       -v "${VOLUME}:/applications" \
       -w "/src" \
       mrcide/shiny-server-builder:latest \
       sync_server
