#!/usr/bin/env bash
set -e

CALLER_UID=`id -u`
CALLER_GID=`id -g`
ROOT=$(realpath $(dirname $0)/..)

docker run --rm -it \
       -e VAULT_AUTH_GITHUB_TOKEN \
       --user="${CALLER_UID}:${CALLER_GID}" \
       -v $ROOT:/target \
       -w /target \
       mrcide/shiny-server-builder:3.5.1 \
       vault_auth
