#!/usr/bin/env bash
set -e
ROOT=$(realpath $(dirname $0)/..)
VAULT_ENV=$ROOT/.vault
CALLER_UID=`id -u`
CALLER_GID=`id -g`

if [[ ! -f $VAULT_ENV ]]; then
    echo "Run ./util/vault_auth to authenticate with vault server"
    exit 1
fi

docker run --rm -it \
       --env-file=$VAULT_ENV \
       -v $ROOT:/target \
       -w /target \
       --user="${CALLER_UID}:${CALLER_GID}" \
       mrcide/shiny-server-builder:{{{twinkle_version}}} \
       configure_apache $*
