#!/usr/bin/env bash
set -e

ROOT=$(realpath $(dirname $0)/..)
VAULT_ENV=$ROOT/.vault

if [[ ! -f $VAULT_ENV ]]; then
    echo "Run ./util/vault_auth to authenticate with vault server"
    exit 1
fi

VOLUME_BASE=$(basename $ROOT)
VOLUME_SOURCE="${VOLUME_BASE}_source"
docker volume create $VOLUME_SOURCE

echo "Provisioning ${ROOT} into ${VOLUME_SOURCE}"

if [ -d ${ROOT}/local ]; then
    VOLUME_LOCAL="-v ${ROOT}/local:/local:ro"
fi

docker run -it --rm \
       --env-file=$VAULT_ENV \
       -v ${VOLUME_SOURCE}:/source \
       -v ${ROOT}/site.yml:/site.yml:ro \
       $VOLUME_LOCAL \
       mrcide/shiny-server-builder:{{{twinkle_version}}} \
       provision_all
