#!/usr/bin/env bash
set -e

ROOT=$(realpath $(dirname $0)/..)
VAULT_ENV=$ROOT/.vault
TWINKLE_TAG=$(cat $ROOT/twinkle_tag)

if [[ ! -f $VAULT_ENV ]]; then
    echo "Run ./util/vault_auth to authenticate with vault server"
    exit 1
fi

VOLUME_BASE=$(basename $ROOT)
VOLUME_STAGING="${VOLUME_BASE}_staging"
docker volume create $VOLUME_STAGING

echo "Provisioning ${ROOT} into ${VOLUME_STAGING}"

if [ -d ${ROOT}/local ]; then
    VOLUME_LOCAL="-v ${ROOT}/local:/local:ro"
fi

docker run --rm \
       --env-file=$VAULT_ENV \
       -v ${VOLUME_STAGING}:/staging \
       -v ${ROOT}/site.yml:/site.yml:ro \
       $VOLUME_LOCAL \
       mrcide/shiny-server-builder:${TWINKLE_TAG} \
       provision $*
