#!/usr/bin/env bash
set -e
ROOT=$(realpath $(dirname $0)/..)
VAULT_ENV=$ROOT/.vault
TWINKLE_TAG=$(cat $ROOT/twinkle_tag)

if [[ ! -f $VAULT_ENV ]]; then
    echo "Run ./scripts/vault_auth to authenticate with vault server"
    exit 1
fi

docker run --rm -it \
       --env-file=$VAULT_ENV \
       mrcide/shiny-server-builder:${TWINKLE_TAG} \
       set_password $*
