#!/usr/bin/env bash
set -e
ROOT=$(realpath $(dirname $0)/..)
VAULT_ENV=$ROOT/.vault

if [[ ! -f $VAULT_ENV ]]; then
    echo "Run ./util/vault_auth to authenticate with vault server"
    exit 1
fi

docker run --rm -it \
       --env-file=$VAULT_ENV \
       mrcide/shiny-server-builder:{{{twinkle_version}}} \
       set_password $*
