#!/usr/bin/env bash
ROOT=$(realpath $(dirname $0)/..)
VOLUME_BASE=$(basename $ROOT)
VOLUME_APPLICATIONS="${VOLUME_BASE}_applications"
VOLUME_SOURCE="${VOLUME_BASE}_source"
if [ -d ${ROOT}/static ]; then
    VOLUME_STATIC="-v ${ROOT}/static:/static:ro"
fi

docker volume create $VOLUME_APPLICATIONS
docker run -it --rm \
       -v "${VOLUME_APPLICATIONS}:/applications" \
       -v "${VOLUME_SOURCE}:/source:ro" \
       $VOLUME_STATIC \
       -v "${ROOT}/site.yml:/site.yml:ro" \
       mrcide/shiny-server-builder:{{{twinkle_version}}} \
       sync_server
